### PR TITLE
Raise proper exception when spectrum is not passed

### LINKED ISSUE #206: Computing VEGAMAG fails when spectrum is not passed
When converting the observed count rate to a magnitude in the Vegamag system , if the Vega spectrum is not provided, it raises an uninformative exception:

MWE:
```python
import os 
import astropy.units as u
import synphot as syn 
import stsynphot as stsyn 


sirius_spec = syn.SourceSpectrum.from_file(os.path.join(os.environ['PYSYN_CDBS'], 'calspec', 'sirius_stis_001.fits')) 
bp_f606w_r05 = stsyn.band('acs, wfc1, f606w, aper#0.5, mjd#58119') 
sirius_f606w = syn.Observation(sirius_spec, bp_f606w_r05, binset=bp_f606w_r05.binset) 
print('{}'.format(sirius_f606w.effstim(syn.units.VEGAMAG, vegaspec=stsyn.Vega))) # Computes as expected 
print('{}'.format(sirius_f606w.effstim(syn.units.VEGAMAG))) # Raises an exception
```

Resulting traceback:
```console
---------------------------------------------------------------------------
IncompatibleSources                       Traceback (most recent call last)
<ipython-input-1-0f91a8802916> in <module>
      9 bp_f606w_r05 = stsyn.band('acs, wfc1, f606w, aper#0.5, mjd#58119')
     10 sirius_f606w = syn.Observation(sirius_spec, bp_f606w_r05, binset=bp_f606w_r05.binset)
---> 11 print('{}'.format(sirius_f606w.effstim(syn.units.VEGAMAG)))

~/miniconda3/envs/astroconda36/lib/python3.6/site-packages/synphot/observation.py in effstim(self, flux_unit, wavelengths, area, vegaspec)
    467         if flux_unit_name == units.VEGAMAG.to_string():
    468             num = self.integrate(wavelengths=wavelengths)
--> 469             den = (vegaspec * self.bandpass).integrate()
    470             utils.validate_totalflux(num)
    471             utils.validate_totalflux(den)

~/miniconda3/envs/astroconda36/lib/python3.6/site-packages/synphot/spectrum.py in __rmul__(self, other)
    398     def __rmul__(self, other):
    399         """This is only called if ``other.__mul__`` cannot operate."""
--> 400         return self.__mul__(other)
    401 
    402     def __truediv__(self, other):  # pragma: no cover

~/miniconda3/envs/astroconda36/lib/python3.6/site-packages/synphot/spectrum.py in __mul__(self, other)
   1293         """Multiply self and other."""
   1294         do_meta_merge = True
-> 1295         self._validate_other_mul_div(other)
   1296 
   1297         if isinstance(other, (u.Quantity, numbers.Number)):

~/miniconda3/envs/astroconda36/lib/python3.6/site-packages/synphot/spectrum.py in _validate_other_mul_div(other)
    380                                   BaseUnitlessSpectrum, SourceSpectrum)):
    381             raise exceptions.IncompatibleSources(
--> 382                 'Can only operate on scalar number/Quantity or spectrum')
    383         elif (isinstance(other, u.Quantity) and
    384               (other.unit.decompose() != u.dimensionless_unscaled or

IncompatibleSources: Can only operate on scalar number/Quantity or spectrum
```

### PR DESCRIPTION
**Pull request by msrdinesh**
This pr is to address the issue [206](https://github.com/spacetelescope/synphot_refactor/issues/206)

EDIT: Fixes #206

### CODE REVIEW

**Comment by msrdinesh** [comment]
Hii mam, I am new to git, please help me how to do it, or share any reference. Thanks!

**Comment by pllim** [comment]
You might want to back up your branch before you do this:
```
git fetch upstream master
git rebase upstream/master
git push -f origin master
```

**Comment by msrdinesh** [comment]
Hii @pllim, I rebased my commit. Also, to close the [206](https://github.com/spacetelescope/synphot_refactor/issues/206), we need to add tests to check whether the exception is raised as you suggested in the comments. If possible please guide me through that also. Thanks!

**Comment by pllim** [comment]
@msrdinesh , try poke around `test_observation.py` and see if you can identify an obvious place to insert a test for this. Thanks! :cat:

**Comment by msrdinesh** [comment]
Hii @pllim, I tried to add the test. There are a couple of errors. Please help me understand where I was wrong. Thanks!

**Comment by pllim** [comment]
@msrdinesh , I don't think the errors are related to your patch. Please rebase again in accordance to https://github.com/spacetelescope/synphot_refactor/pull/228#issuecomment-565516121 and see what happens. Thanks!

**Comment by msrdinesh** [comment]
Wow, it worked like charm! Thank you so much @pllim Please review the pr so, that we can close the issue [206](https://github.com/spacetelescope/synphot_refactor/issues/206).

**Pull request merged**
